# application.yaml
spring:
  application:
    name: backend
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: appuser
    password: secret
